# Generated by Django 5.2.5 on 2025-08-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gheera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('collar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('front', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('side', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gool', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('choras', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pockets', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('knee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('painchra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
