# Generated by Django 5.2.5 on 2025-08-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='collar',
            new_name='paincha',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='painchra',
            new_name='trouser_hip',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='measurement',
            name='trouser_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='trouser_waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='choras',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='gool',
            field=models.BooleanField(default=False),
        ),
    ]
