# Generated by Django 5.2.5 on 2025-08-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='paincha',
            new_name='painchra',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='trouser_hip',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='trouser_length',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='trouser_waist',
        ),
        migrations.AddField(
            model_name='measurement',
            name='collar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='choras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='gool',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
