# Generated by Django 5.2.4 on 2025-08-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gheera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('collar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('front_pocket', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('side_pocket', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gool', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('choras', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trouser_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trouser_waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trouser_hip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pockets', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('knee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paincha', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_measurements', to='customers.customer')),
            ],
        ),
    ]
