# Generated by Django 5.2.4 on 2025-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_measurementform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='length',
            new_name='front_pocket',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='front',
            new_name='paincha',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='painchra',
            new_name='shirt_length',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='side',
            new_name='side_pocket',
        ),
        migrations.AddField(
            model_name='measurement',
            name='trouser_hip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='trouser_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='trouser_waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
