# Generated by Django 5.2.4 on 2025-08-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_length_measurement_front_pocket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='pockets',
        ),
    ]
