# Generated by Django 5.2.4 on 2025-08-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_measurement_pockets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementForm',
        ),
    ]
