# Generated by Django 5.2.5 on 2025-08-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderphasetracking',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='orderphasetracking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderphasetracking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.employee'),
        ),
        migrations.AlterField(
            model_name='orderphasetracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderphasetracking',
            name='phase',
            field=models.CharField(choices=[('MEASUREMENT', 'Measurement'), ('CUTTING', 'Cutting'), ('STITCHING', 'Stitching'), ('FINISHING', 'Finishing'), ('DELIVERY', 'Delivery')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='orderphasetracking',
            name='end_time',
        ),
    ]
