# Generated by Django 5.2.4 on 2025-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cutting', 'Cutting'), ('stitching', 'Stitching'), ('quality', 'Quality Check'), ('kaj_overlock', 'Kaj Overlock'), ('pressing', 'Pressing'), ('packing', 'Packing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
